version: 0.0
os: linux
files:
  - source: /magic8ball
    destination: /var/www/magic8ball
  - source: /magic8ball.conf
    destination: /etc/apache2/sites-available
hooks:
   BeforeInstall:
    - location: scripts/installapache.sh
      runas: root
    - location: scripts/startapache.sh
      runas: root
   AfterInstall:
    - location: scripts/restartapache.sh
      runas: root