version: 0.0
os: linux
files:
  - source: /register
    destination: /var/www/register
  - source: /register.conf
    destination: /etc/apache2/sites-available
hooks:
   BeforeInstall:
    - location: scripts/installapache.sh
      runas: root
    - location: scripts/startapache.sh
      runas: root
   AfterInstall:
    - location: scripts/restartapache.sh
      runas: root